### ISSUE TITLE
Should we close issues on this repository?

### ISSUE THREAD

**Issue by zakkak** [graalvm/graalvm-community-jdk21u#14]
As discussed with @alina-yur, @ezzarghili, and @fniephaus, backport requests or issues related to the community backport repositories should be filed under https://github.com/oracle/graal/ (and tagged accordingly for easier tracking)

To prevent users from opening issues on this repository we need to either disable issues completely on this repository, or update the issue templates to make clear were and how to report what.

Thoughts?

**Comment by alina-yur** [comment]
Hi @zakkak. Yes, I was thinking as well to disable issues and probably add a note in the readme to report them in /graal. wdyt?

**Comment by zakkak** [comment]
Yes, that sounds good to me.

**Comment by zakkak** [comment]
> As discussed with @alina-yur, @ezzarghili, and @fniephaus, backport requests or issues related to the community backport repositories should be filed under https://github.com/oracle/graal/ (and tagged accordingly for easier tracking)

It turns out we won't follow that plan after all, as discussed in https://github.com/oracle/graal/pull/9838#issuecomment-2530927307. As a result we need the issues on this repository :)
